version: 2

jobs:

  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    environment:

    steps:
      - checkout

      - run:
          name: Check versions
          command: |
            node --version
            npm --version
            docker --version
            # yarn --version

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # - run: yarn install
      - run:
          name: Install Packages
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: npm run build

  publish:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - run:
          name: NPM publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish

# Workflows enable multiple jobs in parallel
workflows:
  version: 2

  deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          tags:
            only: /v[0-9]+(\.[0-9]+)*/
